### PR TITLE
Fixed current position issue

### LINKED ISSUE #22: Error: When triggering the shortcut and moving the import to the top, also the editor scroll up now
Since the latest Xcode version it seems like that the editor scroll all the way to the top when entering a new include which makes this plugin quite unusable since you can't keep your focus at the current line.

Is there a cure for this?

### PR DESCRIPTION
**Pull request by clementpadovani**
This fixes #22 

However the issue persists with Xcode 8, however with this code I’m getting no issues with Xcode 9 beta 2.

### CODE REVIEW

File: ImportExtension/AddImportOperation.swift [hunk 1]
```diff
@@ -120,9 +120,12 @@ class AddImportOperation {
         self.buffer.lines.insert(importString, at: line)
         
         //add a new selection. Bug fix for #7
-        let selectionPosition = XCSourceTextRange.init(start: XCSourceTextPosition.init(line: 0, column: 0), end: XCSourceTextPosition.init(line: 0, column: 0))
```
Comment (markohlebar) [inline ImportExtension/AddImportOperation.swift:123]: What happens with the original issue when removing this code?

Comment (clementpadovani) [reply ImportExtension/AddImportOperation.swift:123]: That issue was fixed with Xcode 8.x, I forgot which specific version.

So it _should_ crash on earlier versions of Xcode. However, there shouldn’t be any reason why people are still on old versions of Xcode.

Comment (markohlebar) [reply ImportExtension/AddImportOperation.swift:123]: I'm wondering now if reverting the code pushed to fix #7 would just work for Xcode 9 instead of adding anything new, because I remember it worked fine before that, bar the crash. What worries me as well Xcode 8.x will still be around for at least 2 more months, should we add a regression bug in now?

Comment (clementpadovani) [reply ImportExtension/AddImportOperation.swift:123]: Sorry, I ment to say Xcode 8.3.x; after testing it on Xcode 8.3.3, I was having no issues.

**Comment by markohlebar** [comment]
Ahh I see! Okay I'll check it later today 👍

**Comment by markohlebar** [comment]
Tested this on `8.3.3` and `9.0 beta 2`, works as expected!
